name: Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: lts/*
                  registry-url: https://registry.npmjs.org/

            - run: npm i

            - run: npm i typescript -g

            - run: npm run build

            - run: git config --global user.email "liuqi6602@163.com"

            - run: git config --global user.name "polarove/ci-bot"

            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
